version: '3.9'

services:
  petpet-app:
    image: derek2403/petpet:latest
    container_name: petpet-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Add your environment variables here
      - NEXT_PUBLIC_ALCHEMY_API_KEY=${NEXT_PUBLIC_ALCHEMY_API_KEY:-}
      - BASE_SEPOLIA_RPC=https://base-sepolia.g.alchemy.com/v2/6U7t79S89NhHIspqDQ7oKGRWp5ZOfsNj
    networks:
      - petpet-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optional: Mount volumes if you need persistent data
      - petpet-data:/app/data

networks:
  petpet-network:
    driver: bridge

volumes:
  petpet-data:
    driver: local

